FROM node:alpine as builder
WORKDIR /app
COPY ./package.json ./client
RUN npm install
COPY . .
RUN npm rub build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html

# docker build .
# docker run <image id>
