sudo: required
services:
  - docker

before_install:
  - docker build -t sitvanit/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sitvanit/react-test npm run test -- --coverage

after_success:
  - docker build -t sitvanit/multi-client ./client
  - docker build -t sitvanit/multi-nginx ./nginx
  - docker build -t sitvanit/multi-server ./server
  - docker build -t sitvanit/multi-worker ./worker
  # Log in to docker CLO
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Dockerhub
  - docker push sitvanit/multi-client
  - docker push sitvanit/multi-nginx
  - docker push sitvanit/multi-server
  - docker push sitvanit/multi-worker


